backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :posts
  root "dashboard#index"
  patch "posts/:id/accept", to: "posts#accept", as: :post_accept
  patch "posts/:id/reject", to: "posts#reject", as: :post_reject

  scope :public do
    resources :posts, only: %i[index create], controller: "public/posts"
    get :categories, to: "public/categories#index"
  end
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_paranoid
  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

backend/app/models/lang.rb
class Lang < ActiveRecord::Base
  
end

backend/app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :category
  enum status: %i(rejected pending avaiable)

  scope :filter_by, -> (ids) do
    joins(:category).where(categories: {id: ids})
  end
end

backend/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

backend/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i(edit update destroy)

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new category_params
    if category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if category.update_attributes category_params
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    redirect_to categories_path
  end

  private

  attr_reader :category

  def find_category
    @category = Category.find_by params[:id]
  end

  def category_params
    params.require(:category).permit :name
  end
end

backend/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

backend/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i(edit destroy reject accept)

  def index
    @posts = Post.all
  end

  def reject
    post.rejected!
    redirect_to posts_path
  end

  def accept
    post.avaiable!
    redirect_to posts_path
  end

  def destroy
    post.destroy
    redirect_to posts_path
  end

  private

  attr_reader :post

  def find_post
    @post = Post.find_by params[:id]
  end

  def post_params
    params.require(:post).permit :status
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "app_name"
    return base_title if page_title.empty?
    page_title + " | " + base_title
  end
end

backend/app/views/categories/_form_edit.html.slim
= form_for cate do |f|
  td.text-center
    = cate.id
  td
    .form-group
      = f.text_field :name, class: "form-control"
  td.text-right
    | N/A
  td.row-actions
    = f.submit "Update", class: "btn btn-primary"
    = link_to "Cancel", categories_path, class: "btn btn-white"

backend/app/views/categories/edit.js.erb
var row = '<%= j render "categories/form_edit", cate: @category %>';
console.log(row)
debugger
$("#field-category-<%= @category.id %>").html(row);

backend/app/views/categories/index.html.slim
.content-box
  .row
    .col-sm-12
      .element-wrapper
        .element-actions
        h6.element-header
          | Chuyên mục
        .element-content
          .row
            .table-responsive
              table.table.table-bordered.table-lg.table-v2.table-striped
                thead
                  tr
                    th.text-center
                      | STT
                    th
                      | Category Name
                    th
                      | Posts
                    th
                      | Actions
                tbody
                  - @categories.each do |cate|
                    tr id="field-category-#{cate.id}"
                      td.text-center
                        = cate.id
                      td = cate.name
                      td.text-right
                        | N/A
                      td.row-actions
                        = link_to edit_category_path(cate), remote: true
                          i.os-icon.os-icon-ui-49
                        = link_to category_path(cate), method: :delete, class: "danger", data: { confirm: "Are you sure ?"}
                          i.os-icon.os-icon-ui-15
.content-panel
  .element-wrapper
    h6.element-header
      | Quick Links
    .element-box-tp
      .btn-with-popup
        .form-create-category
          = form_for Category.new do |f|
            .form-group
              = f.label "Category name"
              = f.text_field :name, class: "form-control"
            = f.submit "Create", class: "btn btn-primary"

backend/app/views/categories/new.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

backend/app/views/layouts/_menu_desktop.html.slim
.menu-w.color-scheme-light.color-style-transparent.menu-position-side.menu-side-left.menu-layout-compact.sub-menu-style-over.sub-menu-color-bright.selected-menu-color-light.menu-activated-on-hover.menu-has-selected-link
  .logo-w
    a.logo href="index.html"
    .logo-element
    .logo-label
      | Learn More
  .logged-user-w.avatar-inline
    .logged-user-i
      .avatar-w
        = image_tag "avatar1.jpg"
      .logged-user-info-w
        .logged-user-name
          | Tran Manh Hong
        .logged-user-role
          | Administrator
  h1.menu-page-header
    | Page Header
  ul.main-menu
    li.sub-header
      span
        = t "layouts.content"
    li
      = link_to "#"
        .icon-w
          .os-icon.os-icon-layout
        span
          = t "layouts.category"
      = link_to "#"
        .icon-w
          .os-icon.os-icon-layout
        span
          = t "layouts.language"
      = link_to "#"
        .icon-w
          .os-icon.os-icon-layout
        span
          = t "layouts.post"
    / li.sub-header
    /   span Layouts
    / li.selected.has-sub-menu
    /   a href="index.html"
    /     .icon-w
    /       .os-icon.os-icon-layout
    /     span Dashboard
    /     .sub-menu-w
    /       .sub-menu-header
    /         | Dashboard
    /       .sub-menu-icon
    /         i.os-icon.os-icon-layout
    /       .sub-menu-i
    /         ul.sub-menu
    /           li
    /             a href="index.html"  Dashboard 1
    /           li
    /             a href="apps_crypto.html"
    /               | Crypto Dashboard
    /               strong.badge.badge-danger Hot
    /           li
    /             a href="apps_support_dashboard.html"  Dashboard 3
    /           li
    /             a href="apps_projects.html"  Dashboard 4
    /           li
    /             a href="apps_bank.html"  Dashboard 5
    /           li
    /             a href="layouts_menu_top_image.html"  Dashboard 6

backend/app/views/layouts/_menu_mobile.html.slim
.menu-mobile.menu-activated-on-click.color-scheme-dark
  .mm-logo-buttons-w
    a.mm-logo href="index.html"
      = image_tag "logo.png"
      span Clean Admin
    .mm-buttons
      .content-panel-open
        .os-icon.os-icon-grid-circles
      .mobile-menu-trigger
        .os-icon.os-icon-hamburger-menu-1
  .menu-and-user
    .logged-user-w
      .avatar-w
        = image_tag "avatar1.jpg"
      .logged-user-info-w
        .logged-user-name
          | Maria Gomez
        .logged-user-role
          | Administrator
    ul.main-menu
      li.has-sub-menu
        a href="index.html"
        .icon-w
          .os-icon.os-icon-layout
        span Dashboard
        ul.sub-menu
          li
            a href="index.html"  Dashboard 1
          li
            a href="apps_crypto.html"
              | Crypto Dashboard
              strong.badge.badge-danger Hot
          li
            a href="apps_support_dashboard.html"  Dashboard 3
          li
            a href="apps_projects.html"  Dashboard 4
          li
            a href="apps_bank.html"  Dashboard 5
          li
            a href="layouts_menu_top_image.html"  Dashboard 6

backend/app/views/layouts/application.html.slim
doctype html
html
  head
    title LearnMore
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  body.menu-position-side.menu-side-left.full-screen.with-content-panel
    .all-wrapper.with-side-panel.solid-bg-all
      .layout-w
        = render "layouts/menu_mobile"
        = render "layouts/menu_desktop"
        .content-w
          .top-bar.color-scheme-transparent
            .top-menu-controls
              .element-search.autosuggest-search-activator
                input placeholder=("Nhập vài trường vào...") type="text" /
              .top-icon.top-settings.os-dropdown-trigger.os-dropdown-position-left
                i.os-icon.os-icon-ui-46

              .logged-user-w
                .logged-user-i
                  .avatar-w
                    = image_tag "avatar1.jpg"
                  .logged-user-menu.color-style-bright
                    .logged-user-avatar-info
                      .avatar-w
                        = image_tag "avatar1.jpg"
                      .logged-user-info-w
                        .logged-user-name
                          | Tran Manh Hong
                        .logged-user-role
                          | Administrator
                    .bg-icon
                      i.os-icon.os-icon-wallet-loaded
                    ul
                      li
                        a href="#"
                          i.os-icon.os-icon-signs-11
                          span Thoát
          ul.breadcrumb
            li.breadcrumb-item
              a href="index.html"  Trang chủ
            li.breadcrumb-item
              a href="index.html"  Bài viết
          .content-i
            = yield
            / .content-box
            /   .row
            /     .col-sm-12
            /       .element-wrapper
            /         .element-actions
            /         h6.element-header
            /           | Sales Dashboard
            /         .element-content
            /           .row
            / .content-panel
            /   .element-wrapper
            /     h6.element-header
            /       | Team Members
            /     .element-box-tp

backend/app/views/posts/index.html.erb
<ul>
  <% @posts.each do |l| %>
    <li>
      <%= l.content %> | <%= l.status %>  | <%= link_to "accepr", post_accept_path(l.id), method: :patch %> |
      <%= link_to "reject", post_reject_path(l.id), method: :patch %> |
      <%= link_to "delete", post_path(l.id), method: :delete, data: { confirm: "Are yout sure ?" } %>
    </li>
  <% end %>
</ul>